// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Box: typeof import('./src/components/Box.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/Header.vue')['default']
    LayoutSideBar: typeof import('./src/components/Layout/SideBar.vue')['default']
    NavTitle: typeof import('./src/components/NavTitle.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}

export { }
